apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: voting-app-tls
  namespace: vote-app
spec:
  secretName: voting-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - fhs-vote.diogohack.shop