apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: result-route
  namespace: vote-app   # change if you use default
spec:
  parentRefs:
    - name: voting-app-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /result
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: result-service
          port: 80