apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: voting-httproute
  namespace: vote-app
spec:
  parentRefs:
  - name: voting-app-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /result
    backendRefs:
    - name: result
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: vote
      port: 80
